DEF BATTLETOWER_PARTY_LENGTH EQU 3
DEF BATTLETOWER_STREAK_LENGTH EQU 7

DEF BATTLETOWER_PARTYDATA_SIZE EQU BATTLETOWER_PARTY_LENGTH * 2 ; set + index
DEF BATTLETOWER_SAVEDPARTIES EQU 3 ; to limit repeats

DEF BATTLETOWER_FORCED_LEVEL EQU 50

DEF BATTLETOWER_NUM_TRAINERS EQU 132

; facility brain IDs after regular trainers
	const_def BATTLETOWER_NUM_TRAINERS
	const BATTLETOWER_TOWERTYCOON
	const BATTLETOWER_FACTORYHEAD

DEF BATTLETOWER_NUM_TIERS EQU 4

; sBattleTowerChallengeState values
	const_def
	const BATTLETOWER_NO_CHALLENGE
	const BATTLETOWER_SAVED_AND_LEFT
	const BATTLETOWER_CHALLENGE_IN_PROGRESS
	const BATTLETOWER_LOST_CHALLENGE
	const BATTLETOWER_WON_CHALLENGE

; Special_BattleTower_Battle return values
	const_def
	const BTCHALLENGE_NEXT
	const BTCHALLENGE_FACILITYBRAIN
	const BTCHALLENGE_WON
	const BTCHALLENGE_LOST

; DV set indexes (see data/battle_tower/dvs.asm)
	const_def
	const BTDVS_PERFECT
	const BTDVS_TRICK_ROOM
	const BTDVS_HP_FIGHTING
	const BTDVS_HP_FLYING
	const BTDVS_HP_POISON
	const BTDVS_HP_GROUND
	const BTDVS_HP_ROCK
	const BTDVS_HP_BUG
	const BTDVS_HP_GHOST
	const BTDVS_HP_STEEL
	const BTDVS_HP_FIRE
	const BTDVS_HP_WATER
	const BTDVS_HP_GRASS
	const BTDVS_HP_ELECTRIC
	const BTDVS_HP_PSYCHIC
	const BTDVS_HP_ICE
	const BTDVS_HP_DRAGON
	const BTDVS_HP_DARK
DEF NUM_BTDVS EQU const_value

DEF BATTLETOWER_CHALLENGEMASK EQU %00000111
DEF BATTLETOWER_NORMALMODE    EQU %00000000
DEF BATTLETOWER_RENTALMODE    EQU %00001000
DEF BATTLETOWER_MODEMASK      EQU %00001000

DEF BATTLETOWER_TRAINERMASK   EQU %00000111
DEF BATTLETOWER_SWAPMASK      EQU %00111000

DEF SAFARI_GAUNTLET_KEEP_CAPACITY EQU 30
DEF SAFARI_GAUNTLET_DRAFT_ATTEMPTS EQU 8
DEF SAFARI_GAUNTLET_MIN_TEAM EQU 1
DEF SAFARI_GAUNTLET_DRAFT_LEVEL EQU 50
DEF SAFARI_GAUNTLET_START_LEVEL EQU 55
DEF SAFARI_GAUNTLET_BALLS EQU 46
DEF SAFARI_GAUNTLET_HARD_BALLS EQU 36
DEF SAFARI_GAUNTLET_ROUND_BP EQU 2
DEF SAFARI_GAUNTLET_BOSS_BP EQU 10
DEF SAFARI_GAUNTLET_DRAFT_STEPS EQU 500
DEF SAFARI_GAUNTLET_TM_SHOP_SET_COUNT EQU 3

	const_def
	const SAFARI_GAUNTLET_STEP_IDLE
	const SAFARI_GAUNTLET_STEP_DRAFT
	const SAFARI_GAUNTLET_STEP_ROUND1
	const SAFARI_GAUNTLET_STEP_ROUND2
	const SAFARI_GAUNTLET_STEP_ROUND3
	const SAFARI_GAUNTLET_STEP_ROUND4
	const SAFARI_GAUNTLET_STEP_BOSS

	const_def
	const SAFARI_GAUNTLET_BOSS_FALKNER
	const SAFARI_GAUNTLET_BOSS_BUGSY
	const SAFARI_GAUNTLET_BOSS_WHITNEY
	const SAFARI_GAUNTLET_BOSS_MORTY
	const SAFARI_GAUNTLET_BOSS_CHUCK
	const SAFARI_GAUNTLET_BOSS_JASMINE
	const SAFARI_GAUNTLET_BOSS_PRYCE
	const SAFARI_GAUNTLET_BOSS_CLAIR
	const SAFARI_GAUNTLET_BOSS_BROCK
	const SAFARI_GAUNTLET_BOSS_MISTY
	const SAFARI_GAUNTLET_BOSS_LT_SURGE
	const SAFARI_GAUNTLET_BOSS_ERIKA
	const SAFARI_GAUNTLET_BOSS_JANINE
	const SAFARI_GAUNTLET_BOSS_SABRINA
	const SAFARI_GAUNTLET_BOSS_BLAINE
	const SAFARI_GAUNTLET_BOSS_BLUE
	const SAFARI_GAUNTLET_BOSS_WILL
	const SAFARI_GAUNTLET_BOSS_KOGA
	const SAFARI_GAUNTLET_BOSS_BRUNO
	const SAFARI_GAUNTLET_BOSS_KAREN
	const SAFARI_GAUNTLET_BOSS_LANCE
	const SAFARI_GAUNTLET_BOSS_RED
DEF SAFARI_GAUNTLET_BOSS_COUNT EQU const_value

	const_def
	const SAFARI_GAUNTLET_SETTINGS_NATIONAL_F
	const SAFARI_GAUNTLET_SETTINGS_NO_CARRY_F
	const SAFARI_GAUNTLET_SETTINGS_HIDE_BOSS_F

DEF SAFARI_GAUNTLET_SETTINGS_DIFFICULTY_SHIFT EQU 3
DEF SAFARI_GAUNTLET_SETTINGS_DIFFICULTY_MASK EQU %00011000
DEF SAFARI_GAUNTLET_SETTINGS_DIFFICULTY_CLEAR EQU $ff ^ SAFARI_GAUNTLET_SETTINGS_DIFFICULTY_MASK
DEF SAFARI_GAUNTLET_SETTINGS_KEEPBOX_SEEDED_F EQU 7

	const_def
	const SAFARI_GAUNTLET_DIFFICULTY_STANDARD
	const SAFARI_GAUNTLET_DIFFICULTY_CASUAL
	const SAFARI_GAUNTLET_DIFFICULTY_HARD
